version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "9090:9090"
    volumes:
      - ./audio:/app/audio
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - DEBUG=false
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - WHISPER_MODEL=${WHISPER_MODEL:-tiny}
      - TTS_PROVIDER=${TTS_PROVIDER:-edge}
      - TTS_VOICE=${TTS_VOICE:-en-US}
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=*
    devices:
      - /dev/snd:/dev/snd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
