version: 1
formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(message)s"
  console:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    level: DEBUG
    filename: logs/app.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

loggers:
  root:
    level: INFO
    handlers: [console, file]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: no

  uvicorn.error:
    level: ERROR
    handlers: [console, file]
    propagate: no

  fastapi:
    level: INFO
    handlers: [console, file]
    propagate: no

  structlog:
    level: DEBUG
    handlers: [console, file]
    propagate: no
